name: deg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - conda-forge::pyside2=5.13.2
  - python>3.7, <3.8
  - pytorch::pytorch
  - pip:
    - h5py==2.10.0
    - hydra-core==0.11.3
    - omegaconf==1.4.1
    - matplotlib
    - opencv-python
    - opencv-transforms==0.0.3.post2
    - pandas
    - scikit-learn
    - scipy
    - tifffile
    - tqdm
